#! /usr/bin/perl

use strict;
use warnings;
use FindBin;

BEGIN {
  unshift @INC, "$FindBin::Bin/../lib";
}

use App::webcritic::Critic;
use App::webcritic::Config;

App::webcritic::Critic->new(
  App::webcritic::Config->new(@ARGV)
)->run;