#! /usr/bin/perl

use strict;
use warnings;
use FindBin;
use Pony::Object;

BEGIN {
  $Pony::Object::DEFAULT->{''}->{withExceptions} = 1;
  unshift @INC, "$FindBin::Bin/../lib";
}

use App::webcritic::Critic;
use App::webcritic::Config;
use App::webcritic::Critic::Logger;

App::webcritic::Critic::Logger->new;
App::webcritic::Critic->new(
  App::webcritic::Config->new(@ARGV)
)->run->print_result;