#! /usr/bin/perl

use strict;
use warnings;
use FindBin;
use Pony::Object;

BEGIN {
  $Pony::Object::DEFAULT->{''}->{withExceptions} = 1;
  unshift @INC, "$FindBin::Bin/../lib";
}

use App::webcritic::Critic;
use App::webcritic::Config;

my $config = App::webcritic::Config->new(@ARGV);
App::webcritic::Critic->new($config)->run->print_result;